# Nav2 parameters (ROS 2 Humble)
# Ajuste robot_radius/footprint, frames e limites conforme seu robô.

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.5
      downsample_costmap: false
      allow_unknown: true
      max_iterations: 500000
      max_on_approach_iterations: 1000
      smooth_path: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 15.0
    min_x_velocity_threshold: 0.05
    min_y_velocity_threshold: 0.0
    min_theta_velocity_threshold: 0.1
    progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugins: ["goal_checker"]
    current_goal_checker: "goal_checker"
    
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 1.57
      stateful: True

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      max_linear_accel: 2.5
      max_linear_decel: 2.5
      lookahead_dist: 0.9
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5

      rotate_to_heading_angular_vel: 0.8
      use_rotate_to_heading: true
      allow_reversing: true

      transform_tolerance: 0.5
      regulate_linear_velocity: true
      regulate_angular_velocity: true

      max_allowed_time_to_collision_up_to_carrot: 4.0

behavior_server:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.2
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 2.0

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odometry/filtered   # <-- se o seu odom bom for outro, troque
    transform_tolerance: 0.2
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_w_recovery_and_replanning_only_if_path_becomes_invalid.xml

    # Behaviors padrão do BT
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 10
    stop_on_failure: false

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "CLOSED_LOOP"
    max_velocity: [1.5, 0.0, 1.0]
    min_velocity: [-0.2, 0.0, -0.3]
    max_accel: [1.0, 0.0, 2.5]
    max_decel: [-1.0, 0.0, -2.5]
    odom_topic: /odometry/filtered
    velocity_timeout: 1.0

# ----------------------
# COSTMAPS
# ----------------------

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      footprint: "[[0.49, 0.3725], [0.49, -0.3725], [-0.49, -0.3725], [-0.49, 0.3725]]"
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      update_frequency: 10.0
      publish_frequency: 5.0
      always_send_full_costmap: true
      track_unknown_space: false
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan rgbd_cloud points

        scan:
          topic: /lidar_2d          # ou /lidar_2d (use o que estiver correto)
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05
          obstacle_max_range: 6.0
          obstacle_min_range: 0.20
          raytrace_max_range: 8.0
          raytrace_min_range: 0.20
          clearing: true
          marking: true
          data_type: "LaserScan"
          inf_is_valid: true
        
        rgbd_cloud:
          topic: /camera/points          # PointCloud2 da RGB-D
          data_type: "PointCloud2"
          marking: true
          clearing: false                # ⚠️ NÃO limpar com depth
          obstacle_max_range: 4.0
          obstacle_min_range: 0.30
          max_obstacle_height: 2.0
          min_obstacle_height: 0.12      
          expected_update_rate: 0.0
          observation_persistence: 0.0
        
        points:
          topic: /lidar_3d/points        # PointCloud2 do LIDAR 3D
          data_type: "PointCloud2"
          marking: true
          clearing: false
          obstacle_max_range: 4.0
          obstacle_min_range: 0.30
          max_obstacle_height: 2.0
          min_obstacle_height: 0.12
          expected_update_rate: 0.0
          observation_persistence: 0.0  

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 1.5

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      footprint: "[[0.49, 0.3725], [0.49, -0.3725], [-0.49, -0.3725], [-0.49, 0.3725]]"
      use_sim_time: True
      resolution: 0.05
      track_unknown_space: true
      rolling_window: true
      unknown_cost_value: 255
      width: 200        
      height: 200
      resolution: 0.05
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
        map_topic: /map
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 1.2
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: false
      always_send_full_costmap: True
      introspection_mode: "disabled"